apiVersion: v1
kind: Service
metadata:
  name: mongo
  labels:
    name: mongo
spec:
  ports:
    - port: 27017
      targetPort: 27017
  selector:
    name: mongo
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: mongo
spec:
  replicas: 1
  selector:
    matchLabels:
      name: mongo
  template:
    metadata:
      labels:
        name: mongo
    spec:
      containers:
      - name: mongo
        image: mongo
        ports:
          - containerPort: 27017
        volumeMounts:
          - name: mongo-storage
            mountPath: /data/db
      volumes:
        - name: mongo-storage
          emptyDir: {}            
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: myemp
spec:
  replicas: 1
  selector:
    matchLabels:
      name: myemp
  template:
    metadata:
      labels:
        name: myemp
    spec:
      containers:
      - name: myemp
        image: prasenforu/employee
        ports:
        - containerPort: 8888
---
apiVersion: v1
kind: Service
metadata:
  name: myemp
  labels:
    name: myemp
spec:
  ports:
  - name: 80-tcp
    port: 80
    protocol: TCP
    targetPort: 8888
  selector:
    name: myemp
---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: employee
  annotations:
    kubernetes.io/ingress.class: nginx
spec:
  rules:
    - host: employee.3.16.154.209.nip.io
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: myemp
                port:
                  number: 80
              
